[tox]
; https://www.python.org/downloads/
; https://www.djangoproject.com/download/
minversion = 3.6
envlist =
    py{310,311,312,313}-dj42,
    py{310,311,312,313,314}-dj52,
    py{312,313,314}-dj60,

[testenv]
passenv =
    POSTGRES_HOST
    MYSQL_HOST
    TEST_DATABASE_ENGINE
setenv =
    DJANGO_SETTINGS_MODULE=tests.settings
deps =
    dj42: Django>=4.2,<4.3
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    djmaster: git+https://github.com/django/django
    py{310,311,312,313,314}: -r {toxinidir}/requirements-test.txt
commands =
    py.test --benchmark-skip
