#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive

echo "deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main" \
	> /etc/apt/sources.list.d/postgres.list
wget -O- https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
aptitude --assume-yes update
aptitude --assume-yes install postgresql libpq-dev

sudo -u postgres psql --command "CREATE USER djangorandomqueryset WITH SUPERUSER PASSWORD 'djangorandomqueryset';"
sudo -u postgres createdb --encoding='utf-8' --template=template0 -O djangorandomqueryset djangorandomqueryset

