---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        database_engine:
          - sqlite
          - postgresql
          - mysql
        env:
          - python: "3.9"
            tox-env: "py39-dj32"
          - python: "3.9"
            tox-env: "py39-dj40"

          - python: "3.10"
            tox-env: "py310-dj32"
          - python: "3.10"
            tox-env: "py310-dj40"
          - python: "3.10"
            tox-env: "py310-dj41"

          - python: "3.11"
            tox-env: "py311-dj41"
          - python: "3.11"
            tox-env: "py311-dj42"
          - python: "3.11"
            tox-env: "py311-dj50"
          - python: "3.11"
            tox-env: "py311-dj51"

          - python: "3.12"
            tox-env: "py312-dj42"
          - python: "3.12"
            tox-env: "py312-dj50"
          - python: "3.12"
            tox-env: "py312-dj51"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: django_random_queryset
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_random_queryset
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: django_random_queryset
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.env.python }}

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox -e ${{ matrix.env.tox-env }}
        env:
          POSTGRES_HOST: 127.0.0.1
          MYSQL_HOST: 127.0.0.1
          TEST_DATABASE_ENGINE: ${{ matrix.database_engine }}
